### ISSUE TITLE
AGM?

### ISSUE THREAD

**Issue by WGierke** [RobRomijnders/bigclam#1]
Hey Rob,
Thank you for this repository!
Would you mind explaining what AGM is which is used [here](https://github.com/RobRomijnders/bigclam/blob/master/main.py#L14).
I think a requirements.txt file would make it easier to install dependencies and reproduce your findings :)
Thanks a lot
Willi

**Comment by feknall** [comment]
Hi,
I was working with this project and I understood AGM is something like package name of this project. so, I deleted it and now it's working really well. what I mean is:
`from util.generate_data import Datagen, gen_json`

**Comment by WGierke** [comment]
Thanks @khojir !

**Comment by RobRomijnders** [comment]
Awesome. Thank you for the help!
